name: HuskTownsQuests
main: fr.qg.quests.QuestsPlugin
version: 1.0.0
api-version: '1.21'
authors: ["qg"]
depend: ["HuskTowns"]
libraries:

commands:
  townquests:
    description: Gestion des quêtes de ville
    usage: /<command> start <id> ou list
    aliases:
      - tq
    permission: husktownsquests.command
permissions:
  husktownsquests.command:
    description: Permet d'utiliser la commande /tq
    default: true
